### ISSUE TITLE
chrome.cast.getRouteListElement() returns empty object on iOS

### ISSUE THREAD

**Issue by ghenry22** [jellyfin/cordova-plugin-chromecast#22]
This method on iOS always returns an empty object.

This is the only way to style your own device picker, so we need to standardise this across iOS and android.

**Comment by emilsas** [comment]
When I ran my tests, I obtained the available devices by this function. But I will check it.

Thanks

**Comment by ghenry22** [comment]
@emilsas it seems to always return an empty object, even though you can use the requestSession function to get a list of devices, pick one etc so there are definitely devices valid and available.

**Comment by ghenry22** [comment]
even on Android the info returned isn't particularly useful.  I think we should potentially implement a couple of new more useful functions:
getDeviceList() returns a list of all available devices or an empty list if none (devices should be an object with an id and a friendly name at least)
connectDevice() same as the existing request session but passes in a specific device ID to connect to. 

This provides a headless / API based method to see available devices and connect to one as an alternative to popping up the native dialogues to select.

**Comment by ghenry22** [comment]
@emilsas if you have a chance can you confirm this on iOS?  It returns valid devices on android but on iOS is always an empty object.

**Comment by emilsas** [comment]
@ghenry22 I'd checked this issue, and I got the html element with my available device.

<img width="788" alt="image" src="https://user-images.githubusercontent.com/16924865/64664688-44d27600-d426-11e9-9771-e49ccf61f0e7.png">

**Comment by Lindsay-Needs-Sleep** [comment]
I re-wrote this functionality on Android on my 1.0.0 branch (See Issue #36)
I would like to recommend the api I created on this branch. 

To make your own custom route selector use this:
```
// This will begin an active scan for routes
// routes is an array of { name: "Name of Device", id: routeId }
chrome.cast.cordova.scanForRoutes(function (routes) {
    // Here is where you should update your route selector view with the current routes
    // This will called each time the routes change
});

// When the user selects a route
// stop the scan to save battery power
chrome.cast.cordova.stopScan();

// and use the selected route.id to join the route
chrome.cast.cordova.selectRoute(route.id, function (session) {
    // Save the session for your use
}, function (err) {

});
```


This has some benefits/cons over the previous implementation:
- The routes array is not wrapped in html, this allows easier design flexibility
- The start and stop scan is a bit more cumbersome, but it will save battery life while still returning accurate route lists.
  - Previously, the only way to make the function work as expected was to have the scan running constantly so that the routes list is maintained.
  - But the client must repeatedly call .getRoutes() to keep their list/view maintained.
  - If we do not run the scan constantly, you risk having a completely outdated route list. (possibly the reason for this bug)
- Unfortunately, it is mandatory for the client to be responsible and call stopScan.  If they do not, it will result in increased battery consumption.  (We can call stopScan for them if when they select a route.  This will help a little.  StopScan can be called safely at any time.)
