### ISSUE TITLE
Can't play local videos - Need documentation on how to complete this with external tools

### ISSUE THREAD

**Issue by Lindsay-Needs-Sleep** [jellyfin/cordova-plugin-chromecast#30]
Need to temporarily host local videos on a small server (nanohttpd maybe) and send the hosted url to the cast device to fix this probably.

**Comment by ghenry22** [comment]
Yeh that is exactly what you would have to do as chromecast just wants a URL.

There are quite a few httpd plugins for cordova which can be used to setup a local webserver.  Then the challenge is to keep them alive so that when the cast device wants them it can get them to play the next item in a list for example.

I don't think that this should necessarily be part of this plugin, but a good guide on how to get setup to do this would likely help a lot of people.

**Comment by Lindsay-Needs-Sleep** [comment]
I'm going to close this as I don't think I will be needing to this anymore.  (And so I won't be making a guide.)  But we can re-open this later if needed. 

(It's a pretty niche need probably.)
