### ISSUE TITLE
Duplicate devices in Choose a Chromecast dialog

### ISSUE THREAD

**Issue by lewazo** [jellyfin/cordova-plugin-chromecast#32]
If you have a bunch of Google Home devices on your network and have them in a Group in the Google Home app, you'll see those devices duplicated in the Choose a Chromecast dialog in the Jellyfin Android app.

As you can see from my screenshot below, I have three Google Home speakers

- Salon
- Chambre
- Cuisine

And two Chromecasts

- Télé salon
- Télé chambre

Now, `Salon` and `Chambre` are members of a group called `Maison`. So when you select `Maison`, music is played in sync on both speakers. So that's the expected behaviour.

Now, as you may have noticed, both speakers appears two times. This is because they are part of a group. If I remove one from the Maison group, it will only show once.

I made some changes and will have a PR for this soon.

![Screenshot_20190901-195348](https://user-images.githubusercontent.com/14063312/64083926-cc680880-ccf3-11e9-83cf-17d7df5cac93.png)

**Comment by lewazo** [comment]
Also, just now, I found another cause for this issue.

So when you connect to a device but then force quit the app, that same device will have a duplicate when re-launching the app.

It seems like it creates a route with the description `jellyfin-chromecast`. A potential fix would be to also filter out those, but I can't test this right now. Will check that later.

**Comment by dkanada** [comment]
I'll leave this open for the edge case you mentioned, thanks for the latest changes. Sort by name will be much nicer than the random order.

**Comment by lewazo** [comment]
So, what I gathered when testing this is that when casting something, a route named `jellyfin-chromecast` is created. So for every device currently casting media from Jellyfin, there's going to have this new route.

Obviously this route is then considered to be a device by the plugin and it is shown in the dialog.

By filtering out those with the `jellyfin-chromecast` description we can get rid of them. The problem I have with this solution is that this is a plugin, and not something that is part of the Jellyfin codebase. It would be wrong to have Jellyfin-specific code in here.

I think the solution would be to have the Jellyfin app itself build the Choose a Chromecast dialog using the `chrome.cast.getRouteListElement()` function instead of `chrome.cast.requestSession()`. Of course this would need a lot of refactoring.

Is it something the team could be interested in? If you do, I would love starting to work one that. I use the Android app and chromecast feature a lot so would love to contribute some polish there 😄

**Comment by anthonylavado** [comment]
@lewazo We are always in need of help, and the best way to start is to fix a problem you have. If you're up to it, go for it!

**Comment by Lindsay-Needs-Sleep** [comment]
I believe these problems are fixed on my branch.  
https://github.com/miloproductionsinc/cordova-plugin-chromecast.git#a822f61656583d51bf722c8b4c7d00aec296fffb
This commit in specific.

I just tried the home groups and it looks like this for me:
![Screenshot_20190907-081608](https://user-images.githubusercontent.com/51773923/64476189-25e39380-d149-11e9-8b33-6fee3ff501a5.jpg)

Additionally, I have been fighting with that mysterious 2nd route you mentioned, trying to use so that I could automatically rejoin a session after the the app has been force quit, but I had no luck.  
But the second copy of the route is never displayed by the cast dialog on my branch.

I haven't gotten to re-implementing the function for emiting the routes for customization so it only works for .requestSession().

I would be curious if someone else could test this and make sure it works the way I am also seeing it?

**Comment by lewazo** [comment]
Yeah I believe using the MediaRouteChooserDialog simplifies this a lot. I implemented a fix on my opened PR by checking for an existing SESSION_ID on the route. But I like your solution, I'll try your branch monday
