### ISSUE TITLE
Support of Cast Chrome Sender Framework API

### ISSUE THREAD

**Issue by rbaumi** [jellyfin/cordova-plugin-chromecast#58]
From docs: https://developers.google.com/cast/docs/chrome_sender:

>  The Chrome Sender API consists of two parts: the Framework API (cast.framework) and the Base API (chrome.cast)

Is there any plan to implement first part - Framework API (cast.framework)?

**Comment by Lindsay-Needs-Sleep** [comment]
It's not on my TODO list.  I have been able to do everything my company needs with the Base API.  The only things I have planned for the foreseeable future on my part are bug fixes.

---

Since Google seems to imply that
> In general, you make calls on the simpler, higher-level Framework API [cast.framework], which are then processed by the lower-level Base API [chrome.cast].

it might be possible to implement the framework entirely from the javascript side....  (Which would make it easy-ish potentially.)

But, since this repo is ...extremely lightly maintained, I think supporting less entry points would probably be easiest/best.  
Especially, if the base API can do everything the framework can.
(Not that we currently support all base API functions either :p).

---

What are the reasons you are interested in cast.framework?  
(I haven't used it before so I don't know much)

**Comment by rbaumi** [comment]
Main reason was to make my life easier ;) I have already some piece of code where I'm using cast.framework and I know that in near future i will have to make some cordova based app so I thought of reusing my code. Of course you are completely right - all this can be achieved just bu using base api, I will just have to rewrite some parts of it. 

Thanks for clear answer :) Can be closed!

**Comment by Lindsay-Needs-Sleep** [comment]
Haha, that is an absolutely good reason though!

Thanks. :)
